<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Register_Data.aspx.cs" Inherits="Register_Data" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body bgcolor="darkseagreen">
    <form id="form1" runat="server">
    <div>
        <asp:Button ID="BAdmin" runat="server" BackColor="Orange" BorderColor="Chocolate"
            Font-Bold="True" Font-Size="Large" ForeColor="White" OnClick="BAdmin_Click" Text="Admin" /><br />
        <br />
        <br />
        <br />
        &nbsp;&nbsp;
        <asp:GridView ID="GridView1" runat="server" CellPadding="4" Font-Bold="True" Font-Size="Large"
            ForeColor="#333333" GridLines="None" Height="286px" Width="935px" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing">
            <RowStyle BackColor="#E3EAEB" />
            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <EditRowStyle BackColor="#7C6F57" />
            <AlternatingRowStyle BackColor="White" />
        </asp:GridView>
    
    </div>
    </form>
</body>
</html>
